workflows:
  react_native_workflow:
    name: React Native Build
    max_build_duration: 120
    environment:
      vars:
        NODE_VERSION: 18.17.1
        JAVA_VERSION: 17
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
      
      - name: Build iOS App
        script: |
          cd ios
          pod install --repo-update
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/YourApp.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/YourApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/output
    artifacts:
      - android/app/build/outputs/**/*.apk
      - $CM_BUILD_DIR/output/**/*.ipa
    publishing:
      email:
        recipients:
          - jeremiednl@gmail.com
